"""Safe command entrypoint for agent shell-outs.

Agent panes can drift across directories, and some CLI tool shells do not
reliably preserve every pane environment variable.  A team-scoped wrapper
keeps `claudeteam say/send/read/status` pinned to the team's state and
config instead of falling back to whatever `claudeteam.toml` happens to be
under the current working directory.
"""
from __future__ import annotations

import os
import shlex
import sys
from pathlib import Path

from claudeteam.runtime import paths
from claudeteam.util import atomic_write_text


CONFIG_POINTER_NAME = "config-file.path"


def claudeteam_executable() -> str:
    """Best command spelling for panes whose shell PATH is incomplete."""
    repo_root = Path(__file__).resolve().parents[3]
    candidates = [
        Path(sys.executable).with_name("claudeteam"),
        Path(sys.prefix) / "bin" / "claudeteam",
        repo_root / ".venv" / "bin" / "claudeteam",
    ]
    for candidate in candidates:
        if candidate.exists():
            return str(candidate)
    return "claudeteam"


def config_pointer_path() -> Path:
    return paths.state_file(CONFIG_POINTER_NAME)


def ensure_config_pointer() -> Path:
    """Persist the resolved config file beside the team's state.

    This lets bare commands that still inherit only `CLAUDETEAM_STATE_DIR`
    resolve the right team config even if their cwd is another checkout.
    """
    target = config_pointer_path()
    atomic_write_text(target, str(paths.config_file()) + "\n")
    return target


def wrapper_path() -> Path:
    return paths.state_file("bin/ct")


def _wrapper_script() -> str:
    exports = {
        "CLAUDETEAM_STATE_DIR": str(paths.state_dir()),
        "CLAUDETEAM_CONFIG_FILE": str(paths.config_file()),
    }
    for key in (
        "CLAUDETEAM_TEAM_FILE",
        "CLAUDETEAM_RUNTIME_CONFIG",
        "LARK_CLI_PROFILE",
        "CLAUDETEAM_LARK_CLI_BIN",
    ):
        value = os.environ.get(key)
        if value:
            exports[key] = value
    lines = [
        "#!/bin/sh",
        "# Generated by ClaudeTeam. Pins shell-outs to this team.",
    ]
    for key, value in exports.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    lines.append(f"exec {shlex.quote(claudeteam_executable())} \"$@\"")
    return "\n".join(lines) + "\n"


def ensure_wrapper() -> Path:
    ensure_config_pointer()
    target = wrapper_path()
    atomic_write_text(target, _wrapper_script())
    target.chmod(0o700)
    return target


def safe_cli_cmd(*, ensure: bool = False) -> str:
    if ensure:
        ensure_wrapper()
    return str(wrapper_path())
